# Generated by Django 5.2.3 on 2025-06-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishtype",
            name="country",
        ),
    ]
