# Generated by Django 5.2.3 on 2025-06-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_remove_dishtype_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="license_number",
        ),
    ]
